### PR TITLE
feat!: support private enums

### PR DESCRIPTION
**Pull request by ThinkChaos**
If the enum name starts with a lowercase letter, then all related
symbols are also private.

Also change generated symbols that are meant to be internal to start
with `_` followed by a lower-case letter. These are private regardless
of the enum's visibility.

Some errors are now public (if the enum is) as they seemed likely
relevant to other packages.

---

Kept this in 3 commits to help with review: first is implementation, second is existing tests update, and third is new tests.

This is a breaking change since some function names could change compared to before (if an existing enum is private).

### CODE REVIEW

**Comment by abice** [comment]
Thanks again for putting this up here!

I like the idea of supporting private enums, but I can't support a breaking change like this.  

1) Please revert the change to the internal values with `_` prefixes... this keeps it in line with the `Stringer` tool which was the original intent (I know I've deviated a little, but there's no reason to have them be `_` _and_ lowercased... the point of the underscore is to make them private while keeping the name the same.)

2) I'd rather come up with an opt-in solution for setting up private enums... and this would not be a normal "add a flag" scenario.  I'm thinking more like _per enum_ we should be able to specify... which is a new concept, and needs to be thought out.  A couple options:
  1. Instead of reading `ENUM` read `PRIVATE_ENUM` or some other modifier on top of the definition.  Not my favorite option, but delineates user intent, rather than making assumptions.
  2. Have some other parsing mechanism to add metadata to an enum, meta:private, meta:nocase, meta:some_flag, that way we aren't limiting the possibilities to a single use case, and can add more singular enum functionality down the road.

Thanks again for taking such an interest in the tool!  I love the extra help!

**Comment by ThinkChaos** [comment]
Thanks for taking a look so quickly!

> there's no reason to have them be _ and lowercased

My goal was to be able to tell apart private and "go-enum internal" symbols.  
I went with breaking changes as go-enum is still in pre 1.0 version, doing a `0.6` would allow breaking changes, and IMO the breakage is pretty limited and on symbols users probably don't rely on.  
If you still prefer keeping the old names, maybe it's worth having both names, and marking the existing ones as deprecated? So that deviation can be corrected in the future.

> an opt-in solution for setting up private enums

Relying on the enum name case is already opt-in, and how Go behaves. Why not use that?

**Comment by abice** [comment]
> Thanks for taking a look so quickly!
> 
> > there's no reason to have them be _ and lowercased
> 
> My goal was to be able to tell apart private and "go-enum internal" symbols. I went with breaking changes as go-enum is still in pre 1.0 version, doing a `0.6` would allow breaking changes, and IMO the breakage is pretty limited and on symbols users probably don't rely on. If you still prefer keeping the old names, maybe it's worth having both names, and marking the existing ones as deprecated? So that deviation can be corrected in the future.
> 
> > an opt-in solution for setting up private enums
> 
> Relying on the enum name case is already opt-in, and how Go behaves. Why not use that?

Having a private type, but exported values is a valid use case for enumerations, and if that's how people have been using them, then I don't want to break them from that functionality.  That's not something I'm willing to do.

I'm not a huge fan of the `symbol` method that you've introduced in here either... as it takes away the readability of the template file by having variables that need to be traced back to the origin.  I'm sure it's more of the fact that I'm overly familiar with the templates, but I would rather have that function spread around (which I don't want to do) than have names assigned to a variable to use later.  It makes it harder to track down the problem with the generated code.

I know that there is an inherent "this is pre 1.0, so we can break things" understanding, but as someone who uses this library extensively, I don't want to break my own stuff, let alone others that depend on it.  I know this library is no where near the popularity of logrus or satori.uuid, but both of those libraries did breaking changes, and guess what... I found another solution because it was a good time to try something new.  I would rather continually add opt-in features, and provide easy ways for people to upgrade from one version to another if I need to.

**Comment by ThinkChaos** [comment]
I honestly don't see how a private enum, with public values/funcs is a valid use case. And while it's technically breaking the API, I don't think it's likely to impact anyone.

I'll go ahead and close this since I don't actually require a private enum, it was more of a "would be nice" thing. And don't want to spend time creating a per enum config system.  
Thanks for taking the time to review!

Obviously, feel free to use any of this code if you'd like to base something off of it.

**Pull request closed without merging**
