### PR TITLE
Add support comments in ENUM

### LINKED ISSUE #23: Add support comments in enum
Like 
```
ENUM(
active,
inactive, // no confirmed jobs in last 90 days
invited,
applicant,
deleted,
declined
)
```

### PR DESCRIPTION
**Pull request by GhostRussia**
Update test, snapshots and readme.
Close #23

### CODE REVIEW

**Comment by abice** [comment]
Is this just to support having comments in the definition?  Not to translate them over to the generated enum value?

**Comment by GhostRussia** [comment]
Now yes. I thought about this, if you want, we can also transfer it to the generated file.

**Comment by GhostRussia** [comment]
```
// ColorGreen is a Color of type Green
// {{comment}}
ColorGreen Color = iota + 30
```
or
```
// ColorGreen {{comment}}
ColorGreen Color = iota + 30
```

How to do it better?
I think the first option is better.

**Comment by abice** [comment]
I would be ok with either 2 options:

1. Making the fact that it strips the comments out more prominent in the README
2. Adding the support to transfer the comments to the generated file.

I like the first option as well if you decide to implement the copying.

**Comment by GhostRussia** [comment]
OK. As will have free time, I will try to implement

**Comment by GhostRussia** [comment]
I apologize for the long absence. I will try to start this task next weekend.

**Comment by GhostRussia** [comment]
@abice please check PR

**Comment by GhostRussia** [comment]
I close because I changed the branch

**Pull request closed without merging**
