### PR TITLE
Add uppercase param

### PR DESCRIPTION
**Pull request by o1egl**

### CODE REVIEW

**Comment by abice** [comment]
Hi @o1egl 

Can you give a little info as to why you might need an uppercase version that the lowercase version doesn't already support?

**Comment by abice** [comment]
Also, go ahead and merge master into your fork.  That should make the build work on circle.  Sorry about that!

**Comment by o1egl** [comment]
My case is opposite to the case where you need lowercase param. Enums are defined in lowercase and now I also need to support uppercase aliases.

**Comment by abice** [comment]
Hi @o1egl 

After looking back at the code base, it seems that my implementation of the lower flag was _supposed_ to provide case insensitive lookups for users, not simply to provide a lower case alias of them.  Would modifying the parse function to lookup both lowercase and original value suffice for your use case?  Or do you need an uppercase variant included with nothing allowed in between?

**Comment by o1egl** [comment]
I'm fine having case insensitive lookup option. But let's rename it from `--lower` to `--case-insensitive` or something similar.

**Comment by abice** [comment]
I don't want to break things that are already out there in the world, so renaming isn't something I'm fond of, but we can surely add an alias that makes more sense and does the same thing as `--lower`.

**Comment by abice** [comment]
Finally created a new flag: #45 

@o1egl Let me know if that will solve your problem!

**Comment by o1egl** [comment]
Yes, I think we can close this PR

**Pull request closed without merging**
