### PR TITLE
Add snapshot testing for generated output

### PR DESCRIPTION
**Pull request by bradleyjkemp**
I've recently written a go library ([github.com/bradleyjkemp/cupaloy](https://github.com/bradleyjkemp/cupaloy)) to test exactly this sort of project!

I see you already have a test input that you generate an enum for. This PR adds a snapshot test to check that the generated output doesn't change over time (if you're expecting the output to change as a result of a PR then you simply update the stored snapshot by setting the environment variable UPDATE_SNASPHOTS before running your tests)

### CODE REVIEW

**Comment by abice** [comment]
That looks like a great package to use.  Give me a few days to set up a CI tool and I'll check out what you did!

**Comment by abice** [comment]
@bradleyjkemp I just pulled this down and tested locally... Tests did not pass, and mainly because I've changed the output of the project... which is the point of you're PR, nice work! Can you make sure the circle build will work by using the circleci CLI and running `circleci build` (I know the coveralls part will fail since it doesn't have the repo token)

Thanks!

**Comment by bradleyjkemp** [comment]
Tried running circleci but got a permission denied error. I think only the owner of a repo can use the circle cli?
```go test ./...```  passes fine now though 🙂

**Comment by bradleyjkemp** [comment]
CI only seems to be running on your commits, should it also be testing PRs?

**Comment by abice** [comment]
ha, of course, circle 2.0 doesn't build PRs yet... of course.  Well I'll pull it locally and run in the mean time to be sure.

**Comment by abice** [comment]
Looks good... thanks for the contribution!

**Pull request merged**
