### PR TITLE
Add JSON support

### PR DESCRIPTION
**Pull request by pswaminathan**
Adds support for JSON marshaling and unmarshaling.

### CODE REVIEW

**Comment by abice** [comment]
Sorry for the late response, but the Text marshalling should already take care of this.  Did you try using the `marshal` flag to see if it works for you?  If it doesn't, then I'll surely give this a once over, but as it stands, I've used it plenty of times with json marshalling and it works.

**Comment by abice** [comment]
In fact, there's even a test that checks that json.Unmarshal works: https://github.com/abice/go-enum/blob/9b3947d6d7352bfda7758efc74b8752e6b9e3251/example/commented_test.go#L69-L84

**Comment by pswaminathan** [comment]
Thanks! It never occurred to me that the text marshaling would satisfy JSON marshaling/unmarshaling as well. I feel a little silly now. One thing though that this does not solve is using a value receiver instead of a pointer receiver. I prefer to use value receivers when possible, and pointer receivers when necessary. In order to use `--marshal` as-is, I would only be able to use pointers in my structs, which is non-ideal.

It strikes me that this shouldn't be specific to the marshaling method and should be configurable. Do you have any thoughts on that?

**Comment by abice** [comment]
Are you referring specifically to the pointer receiver on the MarshalText method?

If so, it _used_ to be a lint error to have _all_ pointer receivers or _all_ value receivers.  I think this has since been relaxed and appropriate receivers are allowed.  I think updating this to use a value receiver for the MarshalText would be good.

The pointer receiver on the unmarshal is still required though, as we're modifying the value during the call.

**Comment by pswaminathan** [comment]
Yes, specifically for pointer on MarshalText. Understood for need on Unmarshal.

I’ll open a new PR for it, given it’s pretty divergent from this one.

**Pull request closed without merging**
