### PR TITLE
add support sql scan/value interface

### LINKED ISSUE #25: add support SQL Scan/Value interface
It is necessary to use types in structures that are populated through a database

Now I'm writing this code, but it can be generated like Marshal/UnmarshalText
```go
// ENUM(...)
type TimesheetStatus int

// Scan implements the Scanner interface.
func (x *TimesheetStatus) Scan(value interface{}) error {
	var name string

	switch v := value.(type) {
	case string:
		name = v
	case []byte:
		name = string(v)
	case nil:
		return errors.New("destination pointer is nil")
	}

	tmp, err := ParseTimesheetStatus(name)
	if err != nil {
		return err
	}

	*x = tmp
	return nil
}

// Value implements the driver Valuer interface.
func (x TimesheetStatus) Value() (driver.Value, error) {
	return x.String(), nil
}
```

### PR DESCRIPTION
**Pull request by GhostRussia**
close #25

### CODE REVIEW

**Comment by abice** [comment]
Can you modify or add an example that uses this new option?

**Comment by GhostRussia** [comment]
Conversions using these methods occur when you attempt to write or read a field from a database. Since the ENUM in the database is returned and set as a string, we need to convert the `int` to` string` before sending the data to the database and converting it from `string` to `int` when we read from the database.
I can write an example, but it does not make sense, it works just like `MarshalText`/`UnmarshalText` when we use json, but only for sql.

**Comment by abice** [comment]
I understand how it's used, but I like to keep the example files in the project up to date with various options so that people know what to expect when using a specific command line flag.

**Comment by GhostRussia** [comment]
Ok, I got it

**Comment by GhostRussia** [comment]
Done.

**Comment by GhostRussia** [comment]
conflict resolved

**Pull request merged**
